version: '3'
services:
  app:
    container_name: test_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql          
    networks:
      - fullstack


  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    ports: 
      - 3306:3306
    environment: 
      MYSQL_USER: user
      MYSQL_PASSWORD: user@123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge